import type { MetadataRoute } from "next";

import { siteUrl } from "@/lib/site-config";

// robots.txt.
//
// Built 4 Sep 2026 alongside `sitemap.ts`, for the same reason: the domain is
// connected and the site is now crawlable.
//
// THE SITE IS SERVED ENTIRELY BY A WORKER, which is why this is a route rather
// than a file in `public/`. Cloudflare can inject a managed robots.txt at the
// edge, but every request here reaches the OpenNext worker first, so a
// robots.txt this project does not serve is a robots.txt that may not exist.
// This one is generated by Next and shipped with the app, so it is there
// regardless of what the zone is configured to do.
//
// ─── WHY /what-we-know IS NOT DISALLOWED ────────────────────────────────────
//
// It is the one page on the site we do not want indexed, so `Disallow` looks
// like the obvious move. It is the wrong one, and it would quietly do the
// opposite of what it appears to.
//
// `Disallow` stops a crawler FETCHING a page. `noindex` stops it INDEXING one.
// A crawler that is forbidden to fetch the page never reads the `<meta
// name="robots" content="noindex">` tag it carries — so if the URL is ever
// discovered another way (a link from anywhere, a Search Console submission,
// someone pasting it), Google can index it as a bare URL with no title and no
// description, and will keep it because nothing has told it not to.
//
// Blocking crawling also advertises the path. robots.txt is public: a
// `Disallow: /what-we-know` line is a signpost reading "there is something
// here we would rather you did not read," on a page that is only unlisted, not
// secret.
//
// So the page stays crawlable and says `noindex` in its own head, which is the
// combination Google documents for exactly this case. It is also why the page
// is absent from `sitemap.ts` rather than listed-and-blocked.
//
// ─── WHAT IS BLOCKED ────────────────────────────────────────────────────────
//
// `/api/` only. It holds one POST-only Route Handler for the contact form,
// which answers 405 to the GET a crawler would send. Nothing is protected by
// this line; it saves a pointless request and keeps a 405 out of Search
// Console's coverage report.

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: "/api/",
      },
    ],
    sitemap: `${siteUrl}/sitemap.xml`,
  };
}
